import = [
    "~/.config/alacritty/themes/themes/night_owl.toml"
]


[window]
decorations = "None"
opacity = 0.95
startup_mode = "Maximized"
decorations_theme_variant = "None"
option_as_alt = "Both"

[font]
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }

[colors]
cursor = { text = "CellBackground", cursor = "#CBC3E3"}
