import = [
    "~/.config/alacritty/themes/themes/iterm.toml"
]


[window]
decorations = "Buttonless"
opacity = 0.95
startup_mode = "Maximized"
decorations_theme_variant = "None"
option_as_alt = "Both"

[font]
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }
size = 11.00

[colors]
cursor = { text = "CellBackground", cursor = "#CBC3E3"}

[scrolling]
history = 99999
