[settings]
activate_aggressive = true
experimental = true

[settings.status]
missing_tools = "always"
show_tools = true

[tools]
bun = "latest"
node = "22"
neovim = "latest"
python = "latest"
ripgrep = "13"
yadm = "latest"
yarn = "latest"
zig = "0.13.0"
pnpm = "latest"
